version: "3.9"

services:
  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Admin123
      MYSQL_DATABASE: testdb
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - laesquina_net

  adminer:
    image: adminer
    container_name: adminer_ui
    restart: always
    ports:
      - "8081:8080"   # afuera 8081, adentro 8080
    depends_on:
      - mysql
    networks:
      - laesquina_net

  laesquina:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: laesquina_app
    ports:
      - "5173:5173"
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - laesquina_net

networks:
  laesquina_net:
    driver: bridge
